import 'package:json_annotation/json_annotation.dart';
import '../../addresses/models/address_models.dart';

part 'scan_form_models.g.dart';

/// Shipment reference containing packages included in a SCAN form.
@JsonSerializable(includeIfNull: false)
class ScanFormShipment {
  /// List of USPS tracking numbers included in this manifest.
  final List<String>? trackingNumbers;

  /// Mailer Identification (MID) number.
  @JsonKey(name: 'MID')
  final String? mid;

  /// Manifest Mailer Identification number.
  final String? manifestMID;

  /// Creates a new [ScanFormShipment] instance.
  const ScanFormShipment({
    this.trackingNumbers,
    this.mid,
    this.manifestMID,
  });

  /// Deserializes a JSON map into a [ScanFormShipment].
  factory ScanFormShipment.fromJson(Map<String, dynamic> json) =>
      _$ScanFormShipmentFromJson(json);

  /// Serializes this shipment into a JSON map.
  Map<String, dynamic> toJson() => _$ScanFormShipmentToJson(this);
}

/// Sender details and origin address for a SCAN form.
@JsonSerializable(explicitToJson: true, includeIfNull: false)
class ScanFormFromAddress {
  /// First name of sender.
  final String? firstName;

  /// Last name of sender.
  final String? lastName;

  /// Firm or organization name.
  final String? firm;

  /// Physical postal address details.
  final Address? address;

  /// Creates a new [ScanFormFromAddress] instance.
  const ScanFormFromAddress({
    this.firstName,
    this.lastName,
    this.firm,
    this.address,
  });

  /// Deserializes a JSON map into a [ScanFormFromAddress].
  factory ScanFormFromAddress.fromJson(Map<String, dynamic> json) {
    if (!json.containsKey('address') &&
        (json.containsKey('streetAddress') || json.containsKey('ZIPCode'))) {
      final copy = Map<String, dynamic>.from(json);
      copy['address'] = Address.fromJson(json).toJson();
      return _$ScanFormFromAddressFromJson(copy);
    }
    return _$ScanFormFromAddressFromJson(json);
  }

  /// Serializes this sender info into a JSON map.
  Map<String, dynamic> toJson() => _$ScanFormFromAddressToJson(this);
}

/// Request payload to generate a PS Form 5630 SCAN Form manifest.
@JsonSerializable(explicitToJson: true, includeIfNull: false)
class ScanFormRequest {
  /// USPS Form number (defaults to "5630").
  final String form;

  /// Output image format (e.g. "PDF").
  final String imageType;

  /// Label paper/dimensions layout (e.g. "8.5x11LABEL").
  final String labelType;

  /// Date packages will be mailed (YYYY-MM-DD).
  final String mailingDate;

  /// ZIP code of the postal facility where packages are entered.
  final String entryFacilityZIPCode;

  /// 4-digit ZIP extension for entry facility, if known.
  final String? entryFacilityZIPPlus4;

  /// Destination facility entry type (defaults to "NONE").
  final String destinationEntryFacilityType;

  /// Whether to overwrite existing mailing date.
  final bool overwriteMailingDate;

  /// Packages or MIDs included in this manifest.
  final ScanFormShipment shipment;

  /// Sender name and origin physical address.
  final ScanFormFromAddress fromAddress;

  /// Creates a new [ScanFormRequest] instance.
  const ScanFormRequest({
    this.form = '5630',
    this.imageType = 'PDF',
    this.labelType = '8.5x11LABEL',
    required this.mailingDate,
    required this.entryFacilityZIPCode,
    this.entryFacilityZIPPlus4,
    this.destinationEntryFacilityType = 'NONE',
    this.overwriteMailingDate = false,
    required this.shipment,
    required this.fromAddress,
  });

  /// Deserializes a JSON map into a [ScanFormRequest].
  factory ScanFormRequest.fromJson(Map<String, dynamic> json) =>
      _$ScanFormRequestFromJson(json);

  /// Serializes this request into a JSON map.
  Map<String, dynamic> toJson() => _$ScanFormRequestToJson(this);
}

/// Response returned from the USPS SCAN Form API.
@JsonSerializable(explicitToJson: true, includeIfNull: false)
class ScanFormResponse {
  /// Form type (e.g. "5630").
  final String? form;

  /// Image format of the generated form.
  final String? imageType;

  /// Label type or dimension layout.
  final String? labelType;

  /// Confirmed mailing date.
  final String? mailingDate;

  /// Unique manifest identification number generated by USPS.
  final String? manifestNumber;

  /// List of tracking numbers included in this manifest.
  final List<String>? trackingNumbers;

  /// Base64-encoded PDF or image bytes of the SCAN form, if returned inline.
  final String? labelImage;

  /// Creates a new [ScanFormResponse] instance.
  const ScanFormResponse({
    this.form,
    this.imageType,
    this.labelType,
    this.mailingDate,
    this.manifestNumber,
    this.trackingNumbers,
    this.labelImage,
  });

  /// Deserializes a JSON map into a [ScanFormResponse].
  factory ScanFormResponse.fromJson(Map<String, dynamic> json) =>
      _$ScanFormResponseFromJson(json);

  /// Serializes this response into a JSON map.
  Map<String, dynamic> toJson() => _$ScanFormResponseToJson(this);
}
